package dev.fingertip.core.skill

import dev.fingertip.core.device.ScrollDirection
import dev.fingertip.core.screen.Role
import dev.fingertip.core.screen.Selector
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertIs

/**
 * The JSON shape is a published contract: skills are generated by an agent,
 * reviewed by humans in pull requests, and shipped to devices that may be
 * running an older build. These tests pin the wire format down.
 */
class SkillJsonTest {

    @Test
    fun `decodes the documented wire format`() {
        val json = """
            {
              "id": "whatsapp.read_last_message",
              "version": 3,
              "title": "Read my last WhatsApp message",
              "app": "com.whatsapp",
              "utterances": ["read my last whatsapp message"],
              "steps": [
                { "action": "launch",  "app": "com.whatsapp" },
                { "action": "waitFor", "selector": { "desc": "Conversations" }, "timeoutMs": 10000 },
                { "action": "tap",     "selector": { "role": "LIST_ITEM", "index": 0 } },
                { "action": "capture", "selector": { "role": "LIST_ITEM", "index": -1 }, "as": "message" },
                { "action": "speak",   "template": "Last message: {message}" },
                { "action": "back" }
              ]
            }
        """.trimIndent()

        val skill = SkillJson.decode(json)

        assertEquals("whatsapp.read_last_message", skill.id)
        assertEquals(3, skill.version)
        assertEquals(6, skill.steps.size)
        assertEquals(Launch("com.whatsapp"), skill.steps[0])
        assertEquals(10_000, assertIs<WaitFor>(skill.steps[1]).timeoutMs)
        assertEquals(Role.LIST_ITEM, assertIs<Tap>(skill.steps[2]).selector.role)
        assertEquals("message", assertIs<Capture>(skill.steps[3]).name)
        assertEquals(Back, skill.steps[5])
    }

    @Test
    fun `round trips every step type`() {
        val original = Skill(
            id = "kitchen.sink",
            version = 2,
            title = "Every step",
            app = "com.example",
            utterances = listOf("do everything"),
            notes = "Exercises the full step vocabulary.",
            steps = listOf(
                Launch("com.example"),
                WaitFor(Selector(text = "Ready"), timeoutMs = 1_000, pollMs = 50),
                Tap(Selector(viewId = "go")),
                LongPress(Selector(text = "Item")),
                TypeText(Selector(editable = true), "hello {name}"),
                Scroll(Selector(scrollable = true), ScrollDirection.BACKWARD),
                ScrollUntil(Selector(scrollable = true), Selector(text = "Target"), maxScrolls = 4),
                Back,
                Home,
                Capture(Selector(role = Role.TEXT), name = "name", field = Field.DESC, optional = true),
                Speak("Hi {name}"),
                Sleep(250),
                Assert(Selector(text = "Done"), present = false),
            ),
        )

        val decoded = SkillJson.decode(SkillJson.encode(original))

        assertEquals(original, decoded)
    }

    @Test
    fun `unknown keys are tolerated so older clients survive newer packs`() {
        val json = """
            {
              "id": "future.skill",
              "title": "From a newer build",
              "confidenceHint": 0.9,
              "steps": [
                { "action": "speak", "template": "hello", "emotion": "cheerful" }
              ]
            }
        """.trimIndent()

        val skill = SkillJson.decode(json)

        assertEquals(1, skill.steps.size)
        assertEquals(Speak("hello"), skill.steps.single())
    }

    @Test
    fun `encoded output uses the action discriminator`() {
        val encoded = SkillJson.encode(
            Skill(id = "x", title = "X", steps = listOf(Tap(Selector(text = "Send")))),
        )

        assertContains(encoded, "\"action\": \"tap\"")
    }

    @Test
    fun `a skill with no steps is rejected`() {
        val json = """{ "id": "empty", "title": "Empty", "steps": [] }"""

        val error = kotlin.test.assertFailsWith<IllegalArgumentException> { SkillJson.decode(json) }
        assertContains(error.message ?: "", "no steps")
    }
}
